spring.application.name=servicio-identidad
server.port=8085

# Conexión apuntando al localhost de tu Ubuntu que mapea al Docker
spring.datasource.url=jdbc:mysql://localhost:3306/universidad_backend?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Registro en Eureka apuntando localmente para que se encuentre con el Gateway
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


