# ==========================================
# CONFIGURACIÓN DEL SERVIDOR GATEWAY
# ==========================================
server.port=8090
spring.application.name=api-gateway

# ==========================================
# CONFIGURACIÓN DE RUTAS (ROUTING)
# ==========================================
# 1. Ruta para Identidad / Auth (Corregida para que acepte /api/usuarios/)
spring.cloud.gateway.routes[0].id=servicio-identidad
spring.cloud.gateway.routes[0].uri=lb://servicio-identidad
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/usuarios/**

# 2. Ruta para Menú
spring.cloud.gateway.routes[1].id=servicio-menu
spring.cloud.gateway.routes[1].uri=lb://servicio-menu
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/menu/**

# 3. Ruta para Mesas
spring.cloud.gateway.routes[2].id=servicio-mesas
spring.cloud.gateway.routes[2].uri=lb://servicio-mesas
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/mesas/**

# ==========================================
# CONFIGURACIÓN DE DESCUBRIMIENTO (EUREKA)
# ==========================================
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# CORRECCIÓN: Apuntar al localhost de tu Ubuntu para encontrar a Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true