# Puerto estándar de Eureka
server.port=8761

# Nombre del servicio para que el Gateway lo reconozca
spring.application.name=servidor-eureka

# Eureka no debe registrarse a sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Logs para ver qué pasa
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO
eureka.server.enable-self-preservation=false